### ISSUE TITLE
may I put vim in "Editors"? is a good idea?

### ISSUE THREAD

**Issue by brujo696** [thedevlabs/coders#7]
sometimes I use vim, but I don't know if it is a good idea to add to the list

**Comment by dashr** [comment]
a lot of good coders use vim, but I left it out because it is usually difficult to learn (steep learning curve), its takes a lot of practice. people who have been codingfor a while  or DevOps people will usually pick it up.

**Comment by dashr** [comment]
i also haven't adding any of the usual command line apps, like: nano, cat, more, less, grep. These probably need they own section. We used to have a cheat sheet for it.

**Comment by brujo696** [comment]
ok, thanks
